/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PlaylistRouteImport } from "./routes/playlist"
import { Route as AlbumsRouteImport } from "./routes/albums"
import { Route as IndexRouteImport } from "./routes/index"

const PlaylistRoute = PlaylistRouteImport.update({
  id: "/playlist",
  path: "/playlist",
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: "/albums",
  path: "/albums",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/albums": typeof AlbumsRoute
  "/playlist": typeof PlaylistRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/albums": typeof AlbumsRoute
  "/playlist": typeof PlaylistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/albums": typeof AlbumsRoute
  "/playlist": typeof PlaylistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/albums" | "/playlist"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/albums" | "/playlist"
  id: "__root__" | "/" | "/albums" | "/playlist"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsRoute: typeof AlbumsRoute
  PlaylistRoute: typeof PlaylistRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/playlist": {
      id: "/playlist"
      path: "/playlist"
      fullPath: "/playlist"
      preLoaderRoute: typeof PlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/albums": {
      id: "/albums"
      path: "/albums"
      fullPath: "/albums"
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsRoute: AlbumsRoute,
  PlaylistRoute: PlaylistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
